version: '3.9'
services:
  database:
    image: postgres:alpine
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
  data_commons:
    restart: no
    depends_on:
      database:
        condition: service_healthy
    build: ./
    env_file: .env
    volumes:
      - ./prisma:/app/prisma
  api:
    depends_on:
      - data_commons
    build: ./api
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/app/api
      - ./prisma:/app/prisma
  # TODO: web
  # depends_on:
  # - api
  # build: ./web
  # env_file: .env
  # ports:
  # - ${VITE_PORT}:${VITE_PORT}
  # volumes:
  # - ./web:/app/web
  # - ./prisma:/app/prisma
